# SPDX-FileCopyrightText: Copyright (c) Marcus Holland-Moritz
# SPDX-License-Identifier: MIT

name: "DwarFS CI Build"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "mhx/**"
    tags:
      - v*
    paths-ignore:
      - ".benchmark/**"
      - ".clang-format"
      - ".clang-tidy"
      - ".codacy.yml"
      - ".codecov.yml"
      - ".gitignore"
      - ".maintainer-scripts/**"
      - ".sonarcloud.properties"
      - "CHANGES.md"
      - "CITATION.cff"
      - "README.md"
      - "REUSE.toml"
      - "TODO"
      - "data/**"
      - "doc/completions/**"
      - "doc/perf/**"
      - "doc/*.gif"
      - "doc/*.png"
      - "doc/*.puml"
      - "doc/*.svg"
      - "scripts/**"

permissions:
  contents: read

jobs:
  windows:
    runs-on:
      - self-hosted
      - Windows

    strategy:
      matrix:
        arch:
          - X64
        build_mode:
          - Release
          #- Debug

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: "0"
          ref: ${{ github.ref }}

      - name: Set MSVC Dev Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure Build
        shell: cmd
        run: |
          cmake -B${{ runner.temp }}\build -S${{ runner.workspace }}\dwarfs -GNinja -DCMAKE_MAKE_PROGRAM=C:\bin\ninja.exe -DCMAKE_BUILD_TYPE=${{ matrix.build_mode }} -DWITH_LIBDWARFS=ON -DWITH_TOOLS=OFF -DWITH_FUSE_DRIVER=OFF -DWITH_UNIVERSAL_BINARY=OFF -DWITH_TESTS=OFF -DWITH_BENCHMARKS=OFF -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DVCPKG_INSTALLED_DIR=${{ runner.workspace }}\vcpkg-install-dwarfs -DDWARFS_ARTIFACTS_DIR=Z:\artifacts\dwarfs -DWITH_PXATTR=ON -DENABLE_STACKTRACE=${{ matrix.build_mode == 'Debug' && 'ON' || 'OFF' }}

      - name: Run Build
        shell: cmd
        run: |
          cmake --build ${{ runner.temp }}\build

      #- name: Run Test
      #  shell: cmd
      #  run: |
      #    copy "C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll" ${{ runner.temp }}\build
      #    cmake --build ${{ runner.temp }}\build --target test
      #    cmake --build ${{ runner.temp }}\build --target copy_test_logs

      - name: Build Package
        shell: cmd
        run: |
          cmake --build ${{ runner.temp }}\build --target package

      #- name: Compress Universal Binary
      #  shell: cmd
      #  run: |
      #    cmake --build ${{ runner.temp }}\build --target universal_upx

      - name: Copy Artifacts
        shell: cmd
        run: |
          cmake --build ${{ runner.temp }}\build --target copy_artifacts

      # - name: Prepare Artifact Upload
      #   shell: cmd
      #   run: cat ${{ runner.temp }}\build\artifacts.env >> %GITHUB_ENV%

      # - name: Upload Binary Tarball
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: ${{ env.binary_tarball }}
      #     path: ${{ runner.temp }}\build\${{ env.binary_tarball }}
      #     if-no-files-found: error
      #     compression-level: 0
      #     archive: false
      #   env:
      #     ACTIONS_ARTIFACT_UPLOAD_CONCURRENCY: 5

      # - name: Upload Universal Binary
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: ${{ env.universal_binary }}
      #     path: ${{ runner.temp }}\build\${{ env.universal_binary }}
      #     if-no-files-found: error
      #     compression-level: 0
      #     archive: false
      #   env:
      #     ACTIONS_ARTIFACT_UPLOAD_CONCURRENCY: 5
